### Restaurants Reviews

### 1. Analyze the text reviews to identify the most common positive and negative keywords.

### 2. Calculate the average length of reviews and explore if there is relationship between review length and rating.

In [2]:
# importind required libraries
import pandas as pd

In [3]:
# load data into the file 
Data = pd.read_csv("Dataset .csv")

In [4]:
# type of data
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

### Analyze the text reviews to identify the most common positive and negative keywords.

In [5]:
# Occurrence of a particular reviews.
Data["Rating text"].value_counts()

Rating text
Average      3737
Not rated    2148
Good         2100
Very Good    1079
Excellent     301
Poor          186
Name: count, dtype: int64

In [6]:
# Average votes on a particular review
Data.columns = Data.columns.str.strip()
Text_Reviews = Data.groupby("Rating text")["Votes"].mean().reset_index()
Text_Reviews = Text_Reviews.sort_values(by=["Votes"], ascending=False)
Text_Reviews

  Rating text       Votes
1   Excellent  851.770764
5   Very Good  520.458758
2        Good  229.351429
4        Poor   90.715054
0     Average   48.249130
3   Not rated    0.870112

### Calculate the average length of reviews and explore if there is relationship between review length and rating.

In [7]:
# Calculate the length of each review
Data.columns = Data.columns.str.strip()
Data["Rating text"] = Data["Rating text"].astype(str).apply(len)

# Calculate the average length
average_length = Data["Rating text"].mean()
average_length.round(2)

7.02

###  Relationship between review length and rating.

In [8]:
# Removing the white space
Data.columns = Data.columns.str.strip()

# Grouping "Rating text" categories (e.g., "Excellent", "Good", "Average")
# and calculating the average "Aggregate rating" for each category.
Relationship = Data.groupby("Rating text")["Aggregate rating"].mean().reset_index()
Relationship

   Rating text  Aggregate rating
0            4          3.570691
1            7          3.051619
2            9          1.672336

In [9]:
# the correlation between Rating text and aggregate rating.
Data[["Rating text", "Aggregate rating"]].corr()

                  Rating text  Aggregate rating
Rating text          1.000000         -0.478885
Aggregate rating    -0.478885          1.000000